ERROR_CODES = {
    'PROPERTY_NOT_FOUND': 'PROPERTY_NOT_FOUND',
    'PROPERTY_OFFLINE': 'PROPERTY_OFFLINE',
    'BOOKING_CONFLICT': 'BOOKING_CONFLICT',
    'REPAIR_INVALID': 'REPAIR_INVALID',
    'AUTH_REQUIRED': 'AUTH_REQUIRED',
    'AUTH_INVALID': 'AUTH_INVALID',
    'PERMISSION_DENIED': 'PERMISSION_DENIED',
}
